name = "FileTools"
uuid = "2c042965-b292-4a40-a4a9-3abf2d00bee5"
authors = ["Tsung-Hsi Wu <okatsn@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1.6.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
